server:
  port: 7777

logging:
  path: logs
  file: userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/course?useSSL=false&characterEncoding=UTF-8
    username: root
    password: admin

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
  - mapper/*